service_name: verse_sequel_specs_sqlite
description: Testing of the Sequel SQLite implementation.

logging:
  level: warn
em:
  adapter: local
plugins:
  - name: sequel
    config:
      mode: simple
      db:
        extensions:
          - pg_json
          - pg_array
        adapter: postgres
        user: postgres
        host: localhost
        port: 5432
        database: verse_sequel_test
